apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.serviceName }}
  labels:
    app: {{ .Values.mongodb.serviceName }}
spec:
  replicas: {{ .Values.mongodb.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.serviceName }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.serviceName }}
    spec:
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          ports:
            - containerPort: {{ .Values.mongodb.port }}
              protocol: TCP
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: {{ .Values.mongodb.username }}
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: {{ .Values.mongodb.password }}
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-data
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-data
