apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.serviceName }}
spec:
  type: NodePort
  ports:
    - name: "mongo"
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
  selector:
    app: {{ .Values.mongodb.serviceName }}

