app:
  name: educacionit-app
  image: ppuerta1986/educacionit-app
  replicaCount: 1
  port: 3000

mongodb:
  serviceName: db-server
  image: mongo:7.0
  replicaCount: 1
  port: 27017
  username: root
  password: s3cr3t!
  database: app-desafio10
  storage: 100Mi